dist: precise
language: python
sudo: false
env:
  global:
    - PYTHON_VERSION=3.5
install:
  - wget https://data.qiime2.org/distro/core/qiime2-2018.6-py35-linux-conda.yml
  - conda env create -n qiime2-2018.6 --file qiime2-2018.6-py35-linux-conda.yml
  - rm qiime2-2018.6-py35-linux-conda.yml
script:
  - nosetests
  # - flake8 evident/* setup.py scripts/qiita*
after_success:
  - if [ ${TEST_ADD_STUDIES} == "False" ]; then codecov ; fi
